import type { CSSProperties } from "react"

export const styles: Record<string, CSSProperties> = {
  container: {
    width: 400,
    padding: 20,
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    backgroundColor: "#09090b",
    color: "#fafafa",
    minHeight: 400,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  logo: {
    fontSize: 18,
    fontWeight: 700,
    color: "#fafafa",
  },
  badge: {
    fontSize: 11,
    color: "#a1a1aa",
    backgroundColor: "#18181b",
    padding: "4px 10px",
    borderRadius: 8,
  },
  fieldGroup: {
    marginBottom: 12,
  } as CSSProperties,
  label: {
    display: "block",
    fontSize: 11,
    fontWeight: 600,
    color: "#a1a1aa",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#18181b",
    border: "1px solid #27272a",
    borderRadius: 8,
    color: "#fafafa",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#18181b",
    border: "1px solid #27272a",
    borderRadius: 8,
    color: "#fafafa",
    fontSize: 13,
    outline: "none",
    resize: "vertical",
    minHeight: 60,
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "10px 12px",
    backgroundColor: "#18181b",
    border: "1px solid #27272a",
    borderRadius: 8,
    color: "#fafafa",
    fontSize: 13,
    outline: "none",
    cursor: "pointer",
    boxSizing: "border-box",
    appearance: "none",
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23a1a1aa' stroke-width='2'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E\")",
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
    paddingRight: 32,
  },
  button: {
    width: "100%",
    padding: "12px 20px",
    backgroundColor: "#3b82f6",
    border: "none",
    borderRadius: 10,
    color: "#fff",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 4,
    transition: "background-color 0.15s",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  buttonDisabled: {
    opacity: 0.5,
    cursor: "not-allowed",
  },
  successContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "60px 20px",
    gap: 12,
  },
  successIcon: {
    width: 48,
    height: 48,
    borderRadius: "50%",
    backgroundColor: "#22c55e",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 24,
    color: "#fff",
  },
  successText: {
    fontSize: 16,
    fontWeight: 600,
    color: "#fafafa",
  },
  errorBox: {
    padding: "10px 14px",
    backgroundColor: "#450a0a",
    border: "1px solid #7f1d1d",
    borderRadius: 8,
    color: "#fca5a5",
    fontSize: 12,
    marginTop: 8,
  },
  warningBox: {
    padding: "10px 14px",
    backgroundColor: "#1c1917",
    border: "1px solid #78350f",
    borderRadius: 8,
    color: "#fbbf24",
    fontSize: 12,
    marginTop: 8,
    marginBottom: 12,
  },
  skeleton: {
    height: 14,
    backgroundColor: "#18181b",
    borderRadius: 6,
    animation: "pulse 1.5s ease-in-out infinite",
  },
  requiredStar: {
    color: "#ef4444",
    marginLeft: 2,
  },
}
